ERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Frontend.urls")),
    path('restful/', include("Backend.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Frontend/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib.auth.decorators import login_required, permission_required



urlpatterns = [
    path('', views.Index.as_view(), name="index"),

    path('project_employee_assign_View/<int:id>/',login_required(views.Project_employee_assign_View.as_view()), name='project_employee_assign_View'),

    path('approval_process', login_required(views.Approval_Process.as_view()), name="Approval_Process"),
    path('quotation', login_required(views.Quotation_ListView.as_view()), name="quotation"),
    path('salary/<int:year>/<int:month>/<int:user>', login_required(views.SalaryDetailView.as_view()), name='salary_detail'),
    path('salary/<int:year>/<int:month>', login_required(views.SalaryListView.as_view()), name='salary_list'),

    path('apply_list', login_required(views.Apply_List.as_view()), name="Apply_List"),
    path('approval_list', login_required(views.Approval_List.as_view()), name="Approval_List"),
    path('ExtraWorkDay',login_required( views.ExtraWorkDay_ListView.as_view()), name="ExtraWorkDay"),
    path('Salary_Employees', login_required(views.Salary_Employees_ListView.as_view()), name="Salary_Employees"),
    path('approval_group', login_required(views.Approval_Group.as_view()), name="Approval_Group"),
    path('leave_application', login_required(views.Leave_Application_List.as_view()), name="Leave_Application"),
    path('work_overtime_application',login_required( views.Work_Overtime_Application_List.as_view()), name="Work_Overtime_Application"),
    path('clock_correction_application', login_required(views.Clock_Correction_Application_List.as_view()), name="Clock_Correction_Application"),
    path('leave_param', login_required(views.Leave_Param_List.as_view()), name="Leave_Param"),
    path('calendar',login_required( views.Calendar.as_view()), name="calendar"),
    path('Calendar_list',login_required( views.Calendar_list.as_view()), name="Calendar_list"),
    path('director_Index', login_required(views.Director_Index.as_view()), name="director_Index"),
    path('LaborHealthInfo', login_required(views.LaborHealthInfo_ListView.as_view()), name="LaborHealthInfo"),
    path('profile/', login_required(views.Profile.as_view()), name='profile'),
    path('project-confirmation/', views.Project_Confirmation_ListView.as_view(), name='project-confirmation'),
    path('department/', login_required(views.Department_list.as_view()), name='department'),
    path('equipment/', login_required(views.Equipment_ListView.as_view()), name='equipment'), 
    path('employee/', views.Employee_list.as_view(), name='employee_list'),
    path('employee_attendance/', views.Employee_Attendance_list.as_view(), name='employee_attendance'),
    path('employee_permission/', views.Employee_Permission_list.as_view(), name='employee_permission_list'),
    path('job-assign/', login_required(views.Job_Assign_ListView.as_view()), name='project'),
    path('employee_assign/', login_required(views.Employee_Assign_ListView.as_view()), name='employee_assign'),
    path('work_item/', login_required(views.Work_Item_ListView.as_view()), name='work_item_list'),
    path('client/', login_required(views.Client_ListView.as_view()), name='client_list'),
    path('vehicle/', login_required(views.Vehicle_ListView.as_view()), name='vehicle_list'),
    
    path('ReferenceTable/<str:name>', login_required(views.ReferenceTable_ListView.as_view()), name="ReferenceTable"),
    path('news/', login_required(views.News_ListView.as_view()), name='news'),
    path('TravelApplicationView/', login_required(views.TravelApplicationView.as_view()), name='TravelApplicationView'),
    path('Miss_Food/', login_required(views.Miss_Food_ListView.as_view()), name='Miss_Food'),
    path('accounts/logout/', views.signout, name='logout'),
    #查看單號
    path('clock_correction_application_watch', login_required(views.Clock_Correction_Application_Watch_List.as_view()), name="clock_correction_application_watch"),
    path('leave_application_watch', login_required(views.Leave_Application_Watch_List.as_view()), name="Leave_Application_all"),
    path('work_overtime_application_watch',login_required( views.Work_Overtime_Application_Watch_List.as_view()), name="Work_Overtime_Application_watch"),
    path('TravelApplicationView_watch/', login_required(views.TravelApplicationView_Watch.as_view()), name='TravelApplicationView_watch'),
    path('miss_food_application_watch/', login_required(views.MissFoodApplicationView_Watch.as_view()), name='Miss_Food_Application_watch'),
    path('approval_list_watch', login_required(views.Approval_List_Watch.as_view()), name="approval_list_Watch"),
]

Backend/models.py
from django.db.models.functions import ExtractYear,ExtractMonth,ExtractDay
import json
import math
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from django.db.models.signals import pre_save
from django.db import models
from datetime import time
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django_currentuser.middleware import get_current_authenticated_user
from datetime import date
import os
from datetime import timedelta,datetime

from django.db.models import F, Sum,Q

LOCATION_CHOICES = [
    ("台東", "台東"),
    ("花蓮", "花蓮"),
    ("宜蘭", "宜蘭"),
    ("北北基", "北北基"),
    ("桃園", "桃園"),
    ("新竹", "新竹"),
    ("苗栗", "苗栗"),
    ("台中", "台中"),
    ("南投", "南投"),
    ("彰化", "彰化"),
    ("雲林", "雲林"),
    ("嘉義", "嘉義"),
    ("台南", "台南"),
    ("高雄", "高雄"),
    ("屏東", "屏東"),
    ("花蓮", "花蓮"),
    ("台東", "台東"),
]



class SysMessage(models.Model):
    Target_user = models.ForeignKey("Employee", related_name="sys_messages", on_delete=models.SET_NULL, null=True, blank=True, verbose_name='顯示對象')
    content = models.TextField(verbose_name='內容')
    watch = models.BooleanField(default=False,verbose_name='已看過')

    class Meta:
        verbose_name = '系統消息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content

class UploadedFile(models.Model):
    name = models.CharField(max_length=100)
    file = models.FileField(upload_to='UploadedFile/')
    created_date = models.DateField(default=timezone.now,verbose_name='建立日期')

    class Meta:
        verbose_name = '檔案上傳管理'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name

from django.core.exceptions import PermissionDenied

#紀錄修改者
class ModifiedModel(models.Model):
    modified_by = models.ForeignKey("Employee", on_delete=models.SET_NULL, null=True, blank=True)
    created_date = models.DateField(default=timezone.now,verbose_name='建立日期')
    update_date = models.DateField(auto_now=True, verbose_name='更新日期')

    class Meta:
        abstract = True

    def delete(self, *args, **kwargs):
        if hasattr(self, 'Approval'):  
            if self.Approval:
                current_status = self.Approval.current_status
                if current_status == 'completed' or current_status == 'in_process':
                    raise PermissionDenied("簽核中或簽核完成禁止刪除")
                else: #刪除簽核
                    self.Approval.delete()


        super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        user = get_current_authenticated_user()
        
        if user !=None:
            if hasattr( user,"employee")==False:
                super().save(*args, **kwargs)

            self.modified_by = user.employee

            if hasattr(self, 'created_by'):
                if self.created_by ==None:
                    self.created_by =user.employee
 
        super().save(*args, **kwargs)

    def update_fields_and_save(self, **kwargs):
        if hasattr(self, 'Approval'):
            if self.Approval:
                current_status = self.Approval.current_status
                if current_status == 'completed' or current_status == 'in_process':
                    raise PermissionDenied("簽核中或簽核完成禁止修改.")


        for key, value in kwargs.items():
            setattr(self, key, value)
        self.save()


class ReferenceTable(ModifiedModel):
    location_city_residence = models.CharField(max_length=4, choices=LOCATION_CHOICES, verbose_name="居住地")
    location_city_business_trip = models.CharField(max_length=4, choices=LOCATION_CHOICES, verbose_name="出差地")
    amount = models.DecimalField(verbose_name="錢/單位",max_digits=10, decimal_places=2,default=0)
    name=models.CharField(max_length=10)

    class Meta:
        verbose_name = "參照表"
        verbose_name_plural = "參照表"

    def __str__(self):
        return f"{self.name}參照表 居住地 {self.location_city_residence} / 出差地 {self.location_city_business_trip}  金額 {self.amount}"


#特休紀錄 員工綁AnnualLeave，如果有需要紀錄 可以再擴增記錄某假別欄位
class AnnualLeave(ModifiedModel):
    days = models.IntegerField(default=0, verbose_name="天數")
    end_date = models.DateField( null=True, blank=True,verbose_name='截止日期')
    remark = models.TextField( null=True, blank=True, verbose_name='備註')

    class Meta:
        verbose_name = "特休紀錄表"
        verbose_name_plural = "特休紀錄表"
    def __str__(self):
        user =self.AnnualLeave_user.all()
        if user:
            user=user[0]
        else:
            user =""
        return f"{user} - {self.days}"



# 員工（以內建 User 擴增）
class Employee(ModifiedModel):
    GENDER_CHOICES = [
        ('M', '男'),
        ('F', '女'),
    ]
    BLOOD_TYPE_CHOICES = [
        ('A', 'A型'),
        ('B', 'B型'),
        ('AB','AB型'),
        ('O', 'O型'),
    ]
    MARITAL_STATUS_CHOICES = [
        ('M', '已婚'),
        ('S', '未婚'),
        ('D', '離異'),
    ]
    MILITARY_STATUS_CHOICES = [
        ('M', '義務役'),
        ('E', '免服役'),
        ('A', '替代役'),
    ]   
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='employee_profile/', blank=True, null=True, default='employee_profile/default_profile.png', verbose_name='員工照片')
    location_city = models.CharField(max_length=4, choices=LOCATION_CHOICES, null=True, blank=True, verbose_name='居住城市(用於計算)')
    uploaded_files = models.ManyToManyField(UploadedFile,blank=True,  related_name="userfile")
    annualleaves = models.ManyToManyField(AnnualLeave,blank=True,  related_name="AnnualLeave_user")
    full_name = models.CharField(max_length=30, null=True, blank=True, verbose_name='員工名稱')
    employee_id	 = models.CharField(max_length=30, blank=True,verbose_name='員工編號')
    departments = models.ForeignKey('Department', on_delete=models.SET_NULL, blank=True, null=True, related_name='employees', verbose_name='部門名稱')# 你可以通过department.employees.all()访问一个部门的所有员工。
    position = models.CharField(max_length=30, null=True, blank=True, verbose_name='職稱')
    phone_number = models.CharField(max_length=20, null=True, blank=True,verbose_name='手機號碼')
    contact_number = models.CharField(max_length=20, null=True, blank=True,verbose_name='聯絡電話(報價單顯示)')
    start_work_date = models.DateField(null=True, blank=True, verbose_name='到職日期')
    id_number = models.CharField(max_length=20, null=True, blank=True, verbose_name='身份證字號')
    birthday = models.DateField(null=True, blank=True, verbose_name='出生日期')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True, verbose_name='性別')
    blood_type = models.CharField(max_length=2, choices=BLOOD_TYPE_CHOICES, null=True, blank=True, verbose_name='血型')
    birth_place = models.CharField(max_length=100, null=True, blank=True, verbose_name='出生地')
    marital_status = models.CharField(max_length=1, choices=MARITAL_STATUS_CHOICES, null=True, blank=True, verbose_name='婚姻狀況')
    military_status = models.CharField(max_length=1, choices=MILITARY_STATUS_CHOICES, null=True, blank=True, verbose_name='兵役狀況')
    permanent_address = models.CharField(max_length=50, null=True, blank=True, verbose_name='戶籍地址')
    current_address_city = models.CharField(max_length=50, null=True, blank=True, verbose_name='現居地址縣市')
    current_address = models.CharField(max_length=50, null=True, blank=True, verbose_name='現居地址')
    location = models.CharField(max_length=50, null=True, blank=True, verbose_name='所在地')
    company_email = models.EmailField(null=True, blank=True, verbose_name='公司E_Mail')
    personal_email = models.EmailField(null=True, blank=True, verbose_name='個人E_Mail(報價單顯示)')
    emergency_contact = models.CharField(max_length=50, null=True, blank=True, verbose_name='緊急聯絡人1')
    emergency_contact_relations = models.CharField(max_length=50, null=True, blank=True, verbose_name='關係1')
    emergency_contact_phone = models.CharField(max_length=20, null=True, blank=True, verbose_name='聯絡人電話1')
    default_salary = models.PositiveIntegerField(default=26000, null=True, blank=True, verbose_name="基本薪資")
    job_addition = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name="職務加給")
    phone_addition = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name="手機加給")
    certificates_addition = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name="證照加給")
    labor_protection = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name="勞保級距")
    health_insurance = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name="健保級距")
    labor_pension_moeny = models.PositiveIntegerField(default=6, null=True, blank=True, verbose_name="勞退級距")
    labor_pension = models.PositiveIntegerField(default=6, null=True, blank=True, verbose_name="勞退比例(%)")
    

    class Meta:
        verbose_name = "員工"   # 單數
        verbose_name_plural = verbose_name   #複數

    def get_hour_salary(self):
        return round(self.default_salary / 240, 4)

    @classmethod
    def active_users(cls):
        return cls.objects.filter(user__is_active=True) .exclude(user__username="admin")

    def day_status(self, date): #當天還要上幾小時

        leave_applications = self.leave_list.filter(
            start_date_of_leave__lte=date,
            end_date_of_leave__gte=date,
            Approval__current_status="completed"
        )
        total_hour = 8
        total_minutes = 0
        cost_minutes = 0
        results = []
            
        for leave_application in leave_applications:
            result = leave_application.hour_day(date)
            total_hour -= result["total_hours"]
            cost_minutes += result["total_minutes"]
            results.append(result)       
        
        total_hour -= cost_minutes // 60
        cost_minutes= cost_minutes%60
        if cost_minutes == 30:
            total_hour-=1

Frontend/forms.py
from django import forms
# from .models import

# 登入表單
class LoginForm(forms.Form):

    username = forms.CharField(
        label="帳號",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'id':'username',
                'name':'username'
            })
    )
    password = forms.CharField(
        label="密碼",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'id':'password',
                'name':'password'
            })
    )

Frontend/templates/approval_process/approval_model.html
<ul class="nav nav-tabs" id="myTabs" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="tab1" data-toggle="tab" href="#content1" role="tab"
            aria-controls="content1" aria-selected="true">請假單</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tab2" data-toggle="tab" href="#content2" role="tab"
            aria-controls="content2" aria-selected="false">加班</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tab3" data-toggle="tab" href="#content3" role="tab"
            aria-controls="content3" aria-selected="false">派工單</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tab4" data-toggle="tab" href="#content4" role="tab"
            aria-controls="content4" aria-selected="false">補卡</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tab5" data-toggle="tab" href="#content5" role="tab"
            aria-controls="content5" aria-selected="false">車程津貼</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tab6" data-toggle="tab" href="#content6" role="tab"
            aria-controls="content6" aria-selected="false">誤餐費</a>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane fade show active" id="content1" role="tabpanel" aria-labelledby="tab1">
        請假單
        {% include 'components\leave_application_form.html' %}
    </div>
    <div class="tab-pane fade" id="content2" role="tabpane2" aria-labelledby="tab2">
        加班申請
        {% include 'components\work_overtime_application_form.html' %}
    </div>
    <div class="tab-pane fade" id="content3" role="tabpane3" aria-labelledby="tab3">
        派工單
        {% include 'components\emplooyee_assiag_form.html' %}
    </div>
    <div class="tab-pane fade" id="content4" role="tabpane4" aria-labelledby="tab4">
        補卡單
        {% include 'components\clock_correction_application_form.html' %}
    </div>
    <div class="tab-pane fade" id="content5" role="tabpane5" aria-labelledby="tab5">
        車程津貼
        {% include 'components\travel_application_form.html' %}
    </div>
    <div class="tab-pane fade" id="content6" role="tabpane6" aria-labelledby="tab6">
        誤餐費
        {% include 'components\miss_food_application_form.html' %}
    </div>
</div>

Frontend/templates/approval_process/approval_process.html
{% extends 'base/base_dashboard.html' %}

{% block title %}簽核管理{% endblock %}

{% block import %}

{% load static%}

{% endblock %}


{% load custom_tags %}

{% block main %}




<div class="modal fade" id="approvalModal"  role="dialog" aria-labelledby="approvalModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="approvalModalLabel">簽核處理</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="approval_process_form">
                    <div class="form-group">
                        <label for="status">處理狀態</label>
                        <select class="form-control" id="status" name="status">
                            <option value="-1">選擇狀態</option>
                            <option value="approved">通過</option>
                            <option value="rejected">駁回</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="feedback">回饋</label>
                        <textarea placeholder="可簡單輸入ok、處理狀態、駁回原因等....." class="form-control" id="feedback"
                            name="feedback" rows="3"></textarea>
                    </div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                    <button type="button" id="approval_btn" class="btn btn-primary">提交</button>
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

<div class="modal fade px-3" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">簽核內容</h5>

                <h5 class="my-auto"><a href="" data-toggle="modal" data-target="#approvalModal">點擊簽核</a></h5>

                <h5 id="set_author"> 申請人:王王王</h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            <div class="modal-body">
                {% include 'approval_process\approval_model.html' %}
            </div>
        </div>
    </div>
</div>

<div class="main">


    
    <div class="project-confirmation-table container-fluid shadow-sm table-responsive">
        <table class="table table-sm table-hover text-center" id="table" data-toggle="table" data-sortable="true"
            data-toolbar="#toolbar" data-search="true" data-show-columns="true" data-filter-strict-search="true"
            data-pagination="true" data-page-size="25" data-page-list="[25, All]" data-show-columns-toggle-all="true"
            data-filter-control="true">
            <div id="toolbar">
                {% if error_related_records %}
                {{error_related_records}}
                {% endif %}
            
                <h3>簽核處理</h3>
                <button type="button" class="" onclick="checkpage()">選取/移除當頁資料</button>

                <button class="d-none d-md-inline-block"
                onclick="ApprovalPass('')">一鍵選取處理</button>

            </div>
            <thead class="thead-light" style="font-size: 14px;">
                <tr class="text-nowrap">
                    <th data-force-hide="true" data-switchable="false" data-no-print="true" data-field="checkbox"
                    class="d-none d-md-table-cell">匯出</th>
                    <th data-sortable="true" data-field="type">類型</th>
                    <th data-sortable="true"  data-field="id">編號</th>
                    <th data-sortable="true" data-field="content">內容</th>
                    <th data-sortable="true" data-field="progress">簽核進度</th>
                    <th data-sortable="true" data-field="author">申請人</th>
                    <th data-sortable="true" data-field="process">查看</th>
                </tr>
            </thead>
            <tbody class="" style="font-size: 14px;">
                {% for object in related_records %}
                <tr>
                    <td><input type="checkbox" name="importcheckd" onclick="updateCheckedArray(this)"
                        value="{{ object.id }}"></td>
                    <td>{{ object.target_approval.get_name_display }}</td>
                    <td>{{ object.get_show_id }}</td>
                    <td>
                        {{ object.get_foreignkey.get_show_id }}
                    </td>

                    <td>
                        {% for log in object.get_approval_log_list %}
                        {{ log.show_name }} -
                        {% if log.status == 'pass' %}
                        【{{log.content}}】

                        {% else %}
                        (wait)
                        {% endif %}
                        {% if not forloop.last %} >{% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {{ object.get_foreignkey.created_by.full_name }}
                    </td>
                    <td>
                        <a href="" data-Approval_id="{{ object.id }}"   data-id="{{object.get_foreignkey.id}}"
                        data-created_by="{{ object.get_foreignkey.created_by }}"
                            data-url="{{object.model_url}}" data-toggle="modal" data-target="#myModal">
                            <i class="fa-solid fa-eye fa-lg"></i>
                        </a>
                    </td>

                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>

</div>


<style>
    #approvalModal {
        z-index: 1060;
    }
</style>


<script>


    document.addEventListener('DOMContentLoaded', function () {
        var scripts = [
            "{% static 'js/approval_process/approval_process.js' %}",
            "{% static 'js/approval_process/approval_process_api.js' %}",
            "{% static 'js/fuc/LoadSelect.js' %}",
            "{% static 'js/employee_assign/employee_assign.js' %}",
            "{% static 'js/employee_assign/Equipment.js' %}",
            "{% static 'js/employee_assign/work_tests.js' %}",
            "{% static 'js/fuc/restful.js' %}",
            "{% static 'js/bootstrap-table/checked_row_api.js' %}",
            "{% static 'js/work-overtime-application/work-overtime-application.js' %}",
        ];

        scripts.forEach(function (src) {
            var script = document.createElement('script');
            script.src = src;
            document.body.appendChild(script);
        });
    });

</script>
{% endblock %}